NewsFeed/config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :articles_tags
  resources :follows
  resources :comments
  resources :welcomes
  resources :articles
  resources :sessions
  resources :users

end

NewsFeed/app/models/follow.rb
class Follow < ActiveRecord::Base
  validates :follow, presence: true
  validates :following, presence: true
  belongs_to :following, foreign_key: 'following_id', class_name: 'User'
  belongs_to :follower, foreign_key: 'follower_id', class_name: 'User'
end

NewsFeed/app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :set_user

  before_action :set_user

  def follow_user
    if current_user.follow @user.id
      respond_to do |format|
        format.html { redirect_to @user }
        format.js
      end
    end
  end

  def unfollow_user
    if current_user.unfollow @user.id
      respond_to do |format|
        format.html { redirect_to @user }
        format.js
      end
    end
  end

  def followers
    @followers = @user.followers
  end

  def following
    @followings = @user.following
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
end

NewsFeed/app/helpers/follows_helper.rb
module FollowsHelper
end

NewsFeed/app/views/follows/_form.html.erb
<%= form_for(@follow) do |f| %>
  <% if @follow.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@follow.errors.count, "error") %> prohibited this follow from being saved:</h2>

      <ul>
      <% @follow.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

NewsFeed/app/views/follows/edit.html.erb
<h1>Editing Follow</h1>

<%= render 'form' %>

<%= link_to 'Show', @follow %> |
<%= link_to 'Back', follows_path %>

NewsFeed/app/views/follows/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Follows</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @follows.each do |follow| %>
      <tr>
        <td><%= link_to 'Show', follow %></td>
        <td><%= link_to 'Edit', edit_follow_path(follow) %></td>
        <td><%= link_to 'Destroy', follow, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Follow', new_follow_path %>

NewsFeed/app/views/follows/new.html.erb
<h1>New Follow</h1>

<%= render 'form' %>

<%= link_to 'Back', follows_path %>

NewsFeed/app/views/follows/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_follow_path(@follow) %> |
<%= link_to 'Back', follows_path %>